runtime: python39

env_variables:
  FLASK_ENV: production
  FLASK_DEBUG: false

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto
  secure: always
