# Railway.app Deployment Configuration
# This makes your app permanent and accessible 24/7

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
FLASK_ENV = "production"
PYTHON_VERSION = "3.9"