# Railway.app Deployment Configuration
# This makes your app permanent and accessible 24/7

[build]
builder = "nixpacks"

[deploy]
startCommand = "python schedule_creator_app.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
FLASK_ENV = "production"
PORT = "8080"
PYTHON_VERSION = "3.11"